# Generated by Django 4.0.4 on 2022-05-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='course',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
