# Generated by Django 4.0.4 on 2022-05-22 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faceRecognition', '0003_alter_studentattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('photo_taken', models.ImageField(blank=True, upload_to='attendance_history_photos/')),
                ('course', models.CharField(default='NA', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
                'unique_together': {('user', 'time')},
            },
        ),
    ]
