# Generated by Django 4.0.4 on 2022-05-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecognition', '0005_studentprofile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
