# Generated by Django 3.2.13 on 2022-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecognition', '0008_alter_studentprofile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
